### PR TITLE
Update to BladeCompiler

### PR DESCRIPTION
**Pull request by fridzema**
same issue as https://github.com/404labfr/laravel-impersonate/pull/25, https://github.com/tightenco/ziggy/issues/115, https://github.com/spatie/laravel-blade-javascript/pull/25

### CODE REVIEW

**Comment by denisdulici** [comment]
Robert, can you plz fix the StyleCI conflict?

**Comment by fridzema** [comment]
Don't really know how Styleci works, but code looks good to me tough?

**Comment by devfake** [comment]
Can we please merge this? :)

**Comment by fridzema** [comment]
Sorry for the bunch of commits, but i have figured it out now :)

**Comment by denisdulici** [comment]
Thanks Robert.

**Pull request merged**
